// <auto-generated />
namespace aspnet_mvc5_sample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddNavigationItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNavigationItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201703270208452_AddNavigationItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
